
export const loadEvents = () => {
    let _dispatch, _getState;

    return function (dispatch, getState) {
        _dispatch = dispatch;
        _getState = getState;

        let events = [
            {
                "event_id":"4031",
                "event_type":"night",
                "event_type_alias":"/ibiza-club-tickets/",
                "event_venue_name":"Ibiza Rocks Hotel",
                "event_venue_alias":"ibiza-rocks-hotel/",
                "event_name":"Rudimental & Friends Pool Party",
                "event_alias":"rudimental-friends-pool-party/",
                "event_music_style":"Electronic, Drum & Bass, House",
                "event_opening_hours":"14:00 - 21:00",
                "event_venue_address":"Dr Flemings, 6 - 07820 Ibiza, Spain",
                "event_venue_lat":"38.983014",
                "event_venue_lon":"1.299631",
                "event_slideshow_img_list":"http://www.essentialibiza.com/assets/img/ibiza-club-listings-images/rudimental-friends-pool-party-1.jpg;",
                "event_brand_img":"http://www.essentialibiza.com/assets/img/ibiza-club-listings-images/rudimental-friends-pool-party.jpg",
                "event_short_info":"",
                "event_long_info":"<p>Two Number one Hits, two Number one albums, Sold Out World Tours and an endless supply of energy, its non other than Rudimental, who are back at Ibiza Rocks Hotel this summer for an exclusive 9 week pool party residency. \r\n\r\nTaking over Thursdays, expect some of the best musical talent to be joining the London based drum & Bass group at one of the islands most loved pool party venues.</p>",
                "listing_id":"18883",
                "listing_name":"Rudimental & Friends Closing Party",
                "listing_alias":"rudimental-friends-closing-party/30-August-2018/",
                "listing_ticket_price":"Buy for &euro;25",
                "listing_earlybird_price":"no",
                "listing_earlybird_price_message":"",
                "listing_allocation_warning_message":"",
                "listing_buy_listing_link":"http://www.essentialibiza.com/ibiza-listings-xml/ibiza-club-tickets/rudimental-friends-closing-party/30-August-2018/",
                "listing_buy_tickets_link":"http://www.essentialibiza.com/ibiza-club-tickets/rudimental-friends-closing-party/30-August-2018/",
                "listing_performer_info":"Rudimental, Raye, Mr Eazi, Heartless Crew",
                "listing_date":"THU 30 AUG 2018",
                "listing_date_timestamp":1535587200
            },
            {
                "event_id":"4001",
                "event_type":"night",
                "event_type_alias":"/ibiza-club-tickets/",
                "event_venue_name":"Amnesia",
                "event_venue_alias":"amnesia/",
                "event_name":"Abode / Do Not Sleep",
                "event_alias":"abode-do-not-sleep/",
                "event_music_style":"House & Techno",
                "event_opening_hours":"23:59 - Late",
                "event_venue_address":"Carretera Ibiza a San Antonio Km5, San Rafael 07816, Ibiza",
                "event_venue_lat":"38.947694",
                "event_venue_lon":"1.408288",
                "event_slideshow_img_list":"http://www.essentialibiza.com/assets/img/ibiza-club-listings-images/abode-do-not-sleep-1.jpg;",
                "event_brand_img":"http://www.essentialibiza.com/assets/img/ibiza-club-listings-images/abode-do-not-sleep.jpg",
                "event_short_info":"",
                "event_long_info":"<p>One of the UK's leading House and Techno club nights ABODE will be taking over Thursday night's Ibiza super club Amnesia from June 14th to September 27th 2018. \r\n\r\nWith the legendary Ibiza night Do Not Sleep hosting the infamous Club Room, this promises to be one of the most essential and exciting new nights on the whole of the White Isle.\r\n\r\n</p><p><h2>Your Booking Voucher and Tickets</h2>\r\n<p>Upon purchase you will be receive an instant printable booking voucher by email which will be redeemable for your physical ticket in one of our outlets listed below. All outlets are situated in promenent positions in San Antonio, Ibiza Town, Playa den Bossa and Figueretas. If you pick up your tickets from one of our listed bars you will also be entitiled to a free drink when you present your booking voucher.</p>\r\n<ul>\r\n\t<li><a href=\"https://www.google.com/maps/place/38%C2%B058'44.8%22N+1%C2%B018'23.1%22E/@38.979111,1.306407,17z/data=!4m5!3m4!1s0x0:0x0!8m2!3d38.979111!4d1.306407\" target=\"_blank\">El Kiosko, San Antonio</a></li>\r\n\t<li><a href=\"https://www.google.com/maps/d/viewer?msa=0&mid=1DZSg_bhBP6yG1tBRKYmtwnRgGA0\" target=\"_blank\">Ibiza My Property, Playa d&#39;en Bossa</a></li>\r\n\t<li><a href=\"https://www.google.com/maps/d/viewer?msa=0&mid=13_Rym0R3zhk3roL2XNvzFiuUdLo\" target=\"_blank\">Tantra Caf&eacute;, Playa d&#39;en Bossa</a></li>\r\n\t<li><a href=\"https://www.google.com/maps/d/viewer?ll=38.909671%2C1.438339&spn=0.000538%2C0.001321&msa=0&mid=1JQR2SCmt4rBBDHXX91Wizmy4K3E\" target=\"_blank\">El Chupito Bar, Ibiza Town</a></li>\r\n\t<li><a href=\"https://www.google.com/maps/d/viewer?msa=0&mid=13kqATJoriHm-2OghTSl7JmSKk1c\" target=\"_blank\">Disco Ticket Point, Ibiza Town</a></li>\r\n\t<li><a href=\"https://www.google.com/maps/d/viewer?msa=0&mid=18QKjIvqtamo2VB-n3j4m68CGRss\" target=\"_blank\">El Divino Caf&eacute;, Ibiza Town</a></li>\r\n\t<li><a href=\"https://www.google.com/maps/d/viewer?ll=38.90977%2C1.437704&spn=0.000538%2C%200.001321&msa=0&mid=116Ribrm5YiLhL1_-ZXPjQk1wJwI\" target=\"_blank\">Tango Bar, Ibiza Town</a></li>\r\n\t<li><a href=\"http://maps.google.com/maps/ms?msid=206605360008040890623.0004a6b76f5cf07223835&msa=0\" target=\"_blank\">Zoo Bar, Ibiza Town</a></li>\r\n\t<li><a href=\"https://www.google.com/maps/d/viewer?msa=0&mid=1hxWR9bND0wYqgsDhpxutidgRmy8\" target=\"_blank\">Info Ticket Point, Figueretas</a></li>\r\n</ul></p>",
                "listing_id":"18723",
                "listing_name":"Abode / Do Not Sleep",
                "listing_alias":"abode-do-not-sleep/30-August-2018/",
                "listing_ticket_price":"Buy for &euro;30",
                "listing_earlybird_price":"no",
                "listing_earlybird_price_message":"",
                "listing_allocation_warning_message":"",
                "listing_buy_listing_link":"http://www.essentialibiza.com/ibiza-listings-xml/ibiza-club-tickets/abode-do-not-sleep/30-August-2018/",
                "listing_buy_tickets_link":"http://www.essentialibiza.com/ibiza-club-tickets/abode-do-not-sleep/30-August-2018/",
                "listing_performer_info":"Terrace:, Hosted By Abode, Main Room:, Hosted by Do Not Sleep",
                "listing_date":"THU 30 AUG 2018",
                "listing_date_timestamp":1535587200
            },
            {
                "event_id":"4005",
                "event_type":"night",
                "event_type_alias":"/ibiza-club-tickets/",
                "event_venue_name":"Ibiza Rocks Hotel",
                "event_venue_alias":"ibiza-rocks-hotel/",
                "event_name":"Cuckoo Land",
                "event_alias":"cuckoo-land/",
                "event_music_style":"Urban",
                "event_opening_hours":"14:00 - Late",
                "event_venue_address":"Dr Flemings, 6 - 07820 Ibiza, Spain",
                "event_venue_lat":"38.983014",
                "event_venue_lon":"1.299631",
                "event_slideshow_img_list":"http://www.essentialibiza.com/assets/img/ibiza-club-listings-images/cuckoo-land-1.jpg;http://www.essentialibiza.com/assets/img/ibiza-club-listings-images/cuckoo-land-2.jpg",
                "event_brand_img":"http://www.essentialibiza.com/assets/img/ibiza-club-listings-images/cuckoo-land.jpg",
                "event_short_info":"",
                "event_long_info":"<p>The first year of the House & Techno pool Party Cuckoo Land at Ibiza Rocks was a huge success as one of the stand out pool parties of the season!\r\n\r\nGuaranteed to have a weekly line up of the best in house, tech house and disco under the the sun-drenched sky. Already announced as one of the residents the incredible Sonny Fodera with many more names soon to be announced.</p>",
                "listing_id":"18756",
                "listing_name":"Cuckoo Land",
                "listing_alias":"cuckoo-land/31-August-2018/",
                "listing_ticket_price":"Buy for &euro;15",
                "listing_earlybird_price":"yes",
                "listing_earlybird_price_message":"Very Limited Early Birds Available!",
                "listing_allocation_warning_message":"",
                "listing_buy_listing_link":"http://www.essentialibiza.com/ibiza-listings-xml/ibiza-club-tickets/cuckoo-land/31-August-2018/",
                "listing_buy_tickets_link":"http://www.essentialibiza.com/ibiza-club-tickets/cuckoo-land/31-August-2018/",
                "listing_performer_info":"Line up TBA",
                "listing_date":"FRI 31 AUG 2018",
                "listing_date_timestamp":1535673600
            },
            {
                "event_id":"3947",
                "event_type":"night",
                "event_type_alias":"/ibiza-club-tickets/",
                "event_venue_name":"Benimussa Park",
                "event_venue_alias":"benimussa-park/",
                "event_name":"The Zoo Project",
                "event_alias":"the-zoo-project/",
                "event_music_style":"Underground",
                "event_opening_hours":"16:30 - 23:59",
                "event_venue_address":"Gala Night Park, Carretera Ibiza/San Antonio Km, 12800, 07820 Sant Antoni de Portmany - Ibiza",
                "event_venue_lat":"38.96763417",
                "event_venue_lon":"1.335804462",
                "event_slideshow_img_list":"http://www.essentialibiza.com/assets/img/ibiza-club-listings-images/the-zoo-project-1.jpg;http://www.essentialibiza.com/assets/img/ibiza-club-listings-images/the-zoo-project-2.jpg",
                "event_brand_img":"http://www.essentialibiza.com/assets/img/ibiza-club-listings-images/the-zoo-project.jpg",
                "event_short_info":"",
                "event_long_info":"<p>Since it first opened the gates of the old zoo it has captured the imagination of an ever-increasing army of clubbers. From the uniqueness of the Benimussa Park venue, to the body painting that has become the must-have outfit for the event. From the freedom of partying in the open air, to the amazing line-up of Djs, the Zoo Project brings a must-do experience to Ibiza.<br/><br/>\r\n\r\nZoo Project is back for its <strong>12th consecutive year in 2018</strong> launching on <strong>Saturday June 16th</strong> and running all the way through until <strong>Saturday September 29th</strong>, giving you plenty of opportunity to roar like the lion you are or to howl at the moon to the best underground talent on the planet.<br/><br/>\r\n\r\nThe Zoo Project family have grown their party out of love and dedication over the last decade. They have created a truly unique atmosphere managing to find the perfect combination of <strong>musical programming, consistent creativity</strong> and <strong>performance art</strong>, whilst always keeping the <strong>party spirit at heart</strong>.<br/><br/>\r\n\r\nTickets are <strong>now on sale</strong> for all The Zoo Project Saturday parties and for a limited time are priced at only <strong>15 Euros</strong>. A saving of 35 Euros! VIP tables are also available. <a href=\" http://www.essentialibiza.com/zoo-project-ibiza-vip.asp\">Click Here to book VIP</a>.\r\n\r\nDress code: YOU. Come as you are.<br/><br/></p>",
                "listing_id":"17525",
                "listing_name":"The Zoo Project",
                "listing_alias":"the-zoo-project/01-September-2018/",
                "listing_ticket_price":"Buy for &euro;15",
                "listing_earlybird_price":"yes",
                "listing_earlybird_price_message":"Super early bird ticket. Prices go up soon so book now!",
                "listing_allocation_warning_message":"",
                "listing_buy_listing_link":"http://www.essentialibiza.com/ibiza-listings-xml/ibiza-club-tickets/the-zoo-project/01-September-2018/",
                "listing_buy_tickets_link":"http://www.essentialibiza.com/ibiza-club-tickets/the-zoo-project/01-September-2018/",
                "listing_performer_info":"TBC",
                "listing_date":"SAT 01 SEP 2018",
                "listing_date_timestamp":1535760000
            },
            {
                "event_id":"3947",
                "event_type":"night",
                "event_type_alias":"/ibiza-club-tickets/",
                "event_venue_name":"Benimussa Park",
                "event_venue_alias":"benimussa-park/",
                "event_name":"The Zoo Project Open Air Festival",
                "event_alias":"the-zoo-project/",
                "event_music_style":"Underground",
                "event_opening_hours":"16:30 - 23:59",
                "event_venue_address":"Gala Night Park, Carretera Ibiza/San Antonio Km, 12800, 07820 Sant Antoni de Portmany - Ibiza",
                "event_venue_lat":"38.96763417",
                "event_venue_lon":"1.335804462",
                "event_slideshow_img_list":"http://www.essentialibiza.com/assets/img/ibiza-club-listings-images/the-zoo-project-1.jpg;http://www.essentialibiza.com/assets/img/ibiza-club-listings-images/the-zoo-project-2.jpg",
                "event_brand_img":"http://www.essentialibiza.com/assets/img/ibiza-club-listings-images/the-zoo-project.jpg",
                "event_short_info":"",
                "event_long_info":"<p>Since it first opened the gates of the old zoo it has captured the imagination of an ever-increasing army of clubbers. From the uniqueness of the Benimussa Park venue, to the body painting that has become the must-have outfit for the event. From the freedom of partying in the open air, to the amazing line-up of Djs, the Zoo Project brings a must-do experience to Ibiza.<br/><br/>\r\n\r\nZoo Project Open Air Festival is back for its <strong>12th consecutive year in 2018</strong> launching on <strong>Sunday May 6th</strong> and running all the way through until <strong>Sunday October 7th</strong>, giving you plenty of opportunity to roar like the lion you are or to howl at the moon to the best underground talent on the planet.<br/><br/>\r\n\r\nThe Zoo Project family have grown their party out of love and dedication over the last decade. They have created a truly unique atmosphere managing to find the perfect combination of <strong>musical programming, consistent creativity</strong> and <strong>performance art</strong>, whilst always keeping the <strong>party spirit at heart</strong>.<br/><br/>\r\n\r\nTickets are <strong>now on sale</strong> for all The Zoo Project Saturday parties and for a limited time are priced at only <strong>15 Euros</strong>. A saving of 35 Euros! VIP tables are also available. <a href=\" http://www.essentialibiza.com/zoo-project-ibiza-vip.asp\">Click Here to book VIP</a>.\r\n\r\nDress code: YOU. Come as you are.<br/><br/></p>",
                "listing_id":"18332",
                "listing_name":"The Zoo Project Open Air Festival",
                "listing_alias":"the-zoo-project/02-September-2018/",
                "listing_ticket_price":"Buy for &euro;15",
                "listing_earlybird_price":"yes",
                "listing_earlybird_price_message":"Super early bird ticket. Prices go up soon so book now!",
                "listing_allocation_warning_message":"",
                "listing_buy_listing_link":"http://www.essentialibiza.com/ibiza-listings-xml/ibiza-club-tickets/the-zoo-project/02-September-2018/",
                "listing_buy_tickets_link":"http://www.essentialibiza.com/ibiza-club-tickets/the-zoo-project/02-September-2018/",
                "listing_performer_info":"TBC",
                "listing_date":"SUN 02 SEP 2018",
                "listing_date_timestamp":1535846400
            },
            {
                "event_id":"3960",
                "event_type":"night",
                "event_type_alias":"/ibiza-club-tickets/",
                "event_venue_name":"Eden",
                "event_venue_alias":"eden/",
                "event_name":"Defected in the House",
                "event_alias":"defected-in-the-house/",
                "event_music_style":"House",
                "event_opening_hours":"23:59 - Late",
                "event_venue_address":"San Antonio, Ibiza",
                "event_venue_lat":"38.979034",
                "event_venue_lon":"1.307802",
                "event_slideshow_img_list":"http://www.essentialibiza.com/assets/img/ibiza-club-listings-images/defected-in-the-house-1.jpg;http://www.essentialibiza.com/assets/img/ibiza-club-listings-images/defected-in-the-house-2.jpg;http://www.essentialibiza.com/assets/img/ibiza-club-listings-images/defected-in-the-house-3.jpg;http://www.essentialibiza.com/assets/img/ibiza-club-listings-images/defected-in-the-house-4.jpg",
                "event_brand_img":"http://www.essentialibiza.com/assets/img/ibiza-club-listings-images/defected-in-the-house.jpg",
                "event_short_info":"",
                "event_long_info":"<p><strong>Defected In The House</strong> returns to Ibiza for 2017, moving to its brand new home in San Antonio <strong>Eden Ibiza</strong>.\r\n<br/><br/>\r\nDefected has held Ibiza residencies for 15 years and after a one year break they are back in full force one of San Ann's best spots. At their new home, Defected will have a custom <strong>state of the art VOID sound system</strong> with which to deliver their own unique musical message from <strong>Sunday May 21st </strong> until <strong>Sunday 1st October</strong>. \r\n<br/><br/>\r\nWith an unwavering philosophy that believes that music brings people together and that clubbing experiences should be enjoyable, affordable and inclusive, <strong>Defected In The House</strong> has remained at the forefront of the house scene on and off the island for over a decade and a half. \r\n<br/><br/>\r\nDefected is one of the islands most popular parties, we highly reccomend purchasing tickets in advance!</p>",
                "listing_id":"17872",
                "listing_name":"Defected in the House",
                "listing_alias":"defected-in-the-house/02-September-2018/",
                "listing_ticket_price":"Buy for &euro;20",
                "listing_earlybird_price":"yes",
                "listing_earlybird_price_message":"",
                "listing_allocation_warning_message":"",
                "listing_buy_listing_link":"http://www.essentialibiza.com/ibiza-listings-xml/ibiza-club-tickets/defected-in-the-house/02-September-2018/",
                "listing_buy_tickets_link":"http://www.essentialibiza.com/ibiza-club-tickets/defected-in-the-house/02-September-2018/",
                "listing_performer_info":"TBC",
                "listing_date":"SUN 02 SEP 2018",
                "listing_date_timestamp":1535846400
            },
            {
                "event_id":"4003",
                "event_type":"night",
                "event_type_alias":"/ibiza-club-tickets/",
                "event_venue_name":"Ibiza Rocks Hotel",
                "event_venue_alias":"ibiza-rocks-hotel/",
                "event_name":"Craig David's TS5 Pool Party",
                "event_alias":"craig-davids-ts5-pool-party/",
                "event_music_style":"RnB and Garage",
                "event_opening_hours":"14:00 - Late",
                "event_venue_address":"Dr Flemings, 6 - 07820 Ibiza, Spain",
                "event_venue_lat":"38.983014",
                "event_venue_lon":"1.299631",
                "event_slideshow_img_list":"http://www.essentialibiza.com/assets/img/ibiza-club-listings-images/craig-davids-ts5-pool-party-1.jpg;",
                "event_brand_img":"http://www.essentialibiza.com/assets/img/ibiza-club-listings-images/craig-davids-ts5-pool-party.jpg",
                "event_short_info":"",
                "event_long_info":"<p>For the last summers, RnB/Garage superstar Craig David has sold out week in week out at Ibiza Rocks. So as you can imagine when we heard the news that Ibiza Rocks has bought back one of the best pool parties on the island for 2018, we were extremely happy!</p>",
                "listing_id":"18736",
                "listing_name":"Craig David's TS5 Pool Party",
                "listing_alias":"craig-davids-ts5-pool-party/04-September-2018/",
                "listing_ticket_price":"Buy for &euro;45",
                "listing_earlybird_price":"no",
                "listing_earlybird_price_message":"",
                "listing_allocation_warning_message":"",
                "listing_buy_listing_link":"http://www.essentialibiza.com/ibiza-listings-xml/ibiza-club-tickets/craig-davids-ts5-pool-party/04-September-2018/",
                "listing_buy_tickets_link":"http://www.essentialibiza.com/ibiza-club-tickets/craig-davids-ts5-pool-party/04-September-2018/",
                "listing_performer_info":"Craig David & More TBA",
                "listing_date":"TUE 04 SEP 2018",
                "listing_date_timestamp":1536019200
            },
            {
                "event_id":"4052",
                "event_type":"night",
                "event_type_alias":"/ibiza-club-tickets/",
                "event_venue_name":"Benimussa Park",
                "event_venue_alias":"benimussa-park/",
                "event_name":"Capadi RebelsLand",
                "event_alias":"capadi-rebelsland/",
                "event_music_style":"House & Techno",
                "event_opening_hours":"16:30 - 23:59",
                "event_venue_address":"Gala Night Park, Carretera Ibiza/San Antonio Km, 12800, 07820 Sant Antoni de Portmany - Ibiza",
                "event_venue_lat":"38.96763417",
                "event_venue_lon":"1.335804462",
                "event_slideshow_img_list":"http://www.essentialibiza.com/assets/img/ibiza-club-listings-images/generic/ibiza-tickets-1.jpg;http://www.essentialibiza.com/assets/img/ibiza-club-listings-images/capadi-rebelsland-2.jpg",
                "event_brand_img":"http://www.essentialibiza.com/assets/img/ibiza-club-listings-images/capadi-rebelsland.jpg",
                "event_short_info":"",
                "event_long_info":"<p><strong>Capadi Rebels</strong> move to the iconic open-air venue <strong>Benimussa Park</strong>, having originally established itself on-sea with its infamous boat parties, the <strong>Capadi Rebels</strong> went on to carve a successful residency at underground club <strong>Sankeys</strong> with its conceptual party; <strong>Rebels Cave</strong>. \r\n<br/>\r\nLast year's multi-sensory Cave attracted islanders near and far with its live\r\nperformances and underground techno music. The impressive in-club production   consisted of recycled pieces of art, graffiti (created live) and Persian rugs, while dancing was encouraged barefoot, to make the experience as tribal as possible!. Now, Capadi Rebels will be bringing its eclectic mix of music, art and food out of the cave and onto the land, injecting elements of nature in its latest move to Benimussa.</p>",
                "listing_id":"19170",
                "listing_name":"Capadi RebelsLand",
                "listing_alias":"capadi-rebelsland/04-September-2018/",
                "listing_ticket_price":"Buy for &euro;15",
                "listing_earlybird_price":"yes",
                "listing_earlybird_price_message":"Early Bird Prices SOON TO SELL OUT!",
                "listing_allocation_warning_message":"",
                "listing_buy_listing_link":"http://www.essentialibiza.com/ibiza-listings-xml/ibiza-club-tickets/capadi-rebelsland/04-September-2018/",
                "listing_buy_tickets_link":"http://www.essentialibiza.com/ibiza-club-tickets/capadi-rebelsland/04-September-2018/",
                "listing_performer_info":"Line Up TBA",
                "listing_date":"TUE 04 SEP 2018",
                "listing_date_timestamp":1536019200
            }
        ];

        _dispatch(
            {
                type: 'EVENTS_LOADED',
                events
            }
        );

    };
};
